// Autogenerated from c:\temp\pplarrays.xml
// DO NOT EDIT THIS FILE! Edit c:\temp\pplarrays.xml instead

#ifndef AUTOGENERATED_PPLPROGRAMS_HPP_5ZY4HSUIYKHTPFPN7Q30ROE94YXWQNBI_INCLUDED
#define AUTOGENERATED_PPLPROGRAMS_HPP_5ZY4HSUIYKHTPFPN7Q30ROE94YXWQNBI_INCLUDED

namespace ion {
namespace video {
	class Videodevice;
	class Program;
	class Programarray;
}
}

class PPLPrograms
{
public:

	PPLPrograms(ion::video::Videodevice &rDevice);
	~PPLPrograms();

	ion::video::Programarray& programarray_pplvp();
	const ion::video::Programarray& programarray_pplvp() const;
	ion::video::Program* firstWorkingProgram_pplvp();
	const ion::video::Program* firstWorkingProgram_pplvp() const;

	ion::video::Programarray& programarray_pplfp();
	const ion::video::Programarray& programarray_pplfp() const;
	ion::video::Program* firstWorkingProgram_pplfp();
	const ion::video::Program* firstWorkingProgram_pplfp() const;

protected:
	PPLPrograms(const PPLPrograms& src);
	PPLPrograms& operator =(const PPLPrograms& src);

	ion::video::Programarray* m_pProgramarray_pplvp;
	ion::video::Program* m_pFirstWorkingProgram_pplvp;
	ion::video::Programarray* m_pProgramarray_pplfp;
	ion::video::Program* m_pFirstWorkingProgram_pplfp;
};

#endif
